services:
  nginx:
    build: .
    container_name: nginx_proxy
    ports:
      - "8085:80"
    depends_on:
      - backend

  backend:
    image: traefik/whoami
    container_name: mock_backend
    networks:
      default:
        aliases:
          - node-api
          - dashboard-node-api
          - python-api
          - dashboard-python-api
