services:
  frontend:
    image: nginx:alpine
    container_name: multi_frontend
    ports:
      - "8083:80" # Cambiado para evitar conflicto con 06-nginx-proxy
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html

  backend:
    image: node:20-alpine
    container_name: multi_backend
    ports:
      - "3003:3000" # Cambiado para evitar conflicto con grafana en 08-prometheus-grafana
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"

  db:
    image: mongo:7
    container_name: multi_db
    ports:
      - "27017:27017"