services:
  api:
    build: .
    container_name: postgres_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:pass@postgres/db
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_api_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"