version: "3.8"
services:
  db:
    image: mariadb:10.6
    container_name: php_lamp_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT:-rootpass}
      MARIADB_DATABASE: ${DB_NAME:-appdb}
      MARIADB_USER: ${DB_USER:-appuser}
      MARIADB_PASSWORD: ${DB_PASS:-apppass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./docker/php
    container_name: php_lamp_web
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-appdb}
      DB_USER: ${DB_USER:-appuser}
      DB_PASS: ${DB_PASS:-apppass}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_lamp_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER:-appuser}
      PMA_PASSWORD: ${DB_PASS:-apppass}
    depends_on:
      - db

volumes:
  db_data:
