services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_monitoring
    ports:
      - "3002:3000" # Cambiado para evitar conflicto con el backend de 09-multi-service-app
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin