global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-api'
    static_configs:
      - targets: ['node-api:3000']
  - job_name: 'python-api'
    static_configs:
      - targets: ['python-api:5000']